services:
  nginx:
    image: nginx:1.25-alpine
    ports:
      - "8090:80"
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  php:
    build:
      context: ./docker/php
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/zz-custom.ini:ro
    depends_on:
      - db

  db:
    image: mysql:8.0
    command: >
      --default-authentication-plugin=mysql_native_password
      --sql_mode=
      --innodb_buffer_pool_size=512M
      --innodb_flush_log_at_trx_commit=2
      --sync_binlog=0
    environment:
      MYSQL_DATABASE: bitrix
      MYSQL_USER: bitrix
      MYSQL_PASSWORD: bitrix
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "33160:3306"
    volumes:
      - dbdata:/var/lib/mysql

  adminer:
    image: adminer:4
    ports:
      - "8091:8080"
    depends_on:
      - db

volumes:
  dbdata: